=== sagardokhale29/AllPreparationWork/xmldemo/src/bookinfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bookdetails (book*)>
<!ELEMENT book (code,name,price,publish-date )>
<!ELEMENT code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT publish-date (dd,mm,yy)>
<!ELEMENT dd (#PCDATA)>
<!ELEMENT mm (#PCDATA)>
<!ELEMENT yy (#PCDATA)>

=== sagardokhale29/AllPreparationWork/xmldemo/bin/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookdetails SYSTEM "bookinfo.dtd" >
<bookdetails>
 <book>
 <code>101</code>
 <name>java</name>
 <price>299</price>
 <publish-date>
 <dd>22</dd>
 <mm>3</mm>
 <yy>2006</yy>
 </publish-date>
 </book>
 <book>
 <code>102</code>
 <name>c++</name>
 <price>300</price>
 <publish-date>
 <dd>22</dd>
 <mm>8</mm>
 <yy>1991</yy>
 </publish-date>
 </book>
 <book>
 	<code>100</code>
 	<name>adv java</name>
 	<price>200</price>
 	<publish-date>
 		<dd>4</dd>
 		<mm>5</mm>
 		<yy>1992</yy>
 	</publish-date>
 </book>

</bookdetails>
